# Generated by Django 4.2.7 on 2025-02-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_patientinfo_medicalhistory_currentsymptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='Patientid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
