# Generated by Django 4.2.7 on 2025-03-28 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_patientinfo_patientid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentSymptoms',
            new_name='Diagnosis',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='Symptoms',
            new_name='Diagnosis',
        ),
        migrations.RenameField(
            model_name='patientinfo',
            old_name='Patientid',
            new_name='CrNo',
        ),
        migrations.RemoveField(
            model_name='patientinfo',
            name='RecentVisit',
        ),
        migrations.DeleteModel(
            name='BloodReport',
        ),
    ]
