# Generated by Django 4.2.7 on 2025-03-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_currentsymptoms_diagnosis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='patient',
            new_name='CrNo',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='patient',
            new_name='CrNo',
        ),
    ]
