# Generated by Django 4.2.7 on 2025-03-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_rename_patient_diagnosis_crno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('doctor', 'doctor')], max_length=19),
        ),
    ]
