# Generated by Django 4.2.7 on 2025-03-28 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentVists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecentVisit', models.DateField()),
                ('Followup', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='ReferredDoctor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='CrNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='data.patientinfo'),
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
        migrations.AddField(
            model_name='recentvists',
            name='CrNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_visists', to='data.patientinfo'),
        ),
    ]
