# Generated by Django 4.2.7 on 2025-03-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_recentvists_patientinfo_referreddoctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
