# Generated by Django 4.2.7 on 2025-04-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinfo',
            old_name='ReferredDoctor',
            new_name='ConsultingDoctor',
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='Diagnosis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='FirstVisit',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=70),
        ),
    ]
