# Generated by Django 4.2.7 on 2025-04-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_rename_referreddoctor_patientinfo_consultingdoctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
