# Generated by Django 4.2.7 on 2025-04-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_alter_customuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default='ririana', max_length=20),
        ),
    ]
