# Generated by Django 4.2.7 on 2025-04-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_customuser_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
    ]
