# Generated by Django 4.2.7 on 2025-04-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_remove_customuser_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentvists',
            name='Followup',
            field=models.CharField(default=0),
        ),
    ]
