# Generated by Django 4.2.7 on 2025-07-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_alter_recentvists_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
