# Generated by Django 4.2.7 on 2025-07-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=4)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
